# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_message_secretmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretManager',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='likers',
            new_name='likes',
        ),
    ]
